version: "3.9"

services:
  frontend:
    container_name: frontend
    build:
      context: .
      dockerfile: ./apps/frontend/Dockerfile
    ports:
      - "80:80"
    networks:
      - odin
    volumes:
      - ./apps/frontend:/app
  backend:
    container_name: backend
    build:
      context: .
      dockerfile: ./apps/backend/Dockerfile

    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=message_integration
    ports:
      - "3000:3000"
    depends_on:
      - db
    networks:
      - odin

  db:
    container_name: database
    image: postgres:alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: message_integration
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - odin

networks:
  odin:
    external: false
    driver: bridge

volumes:
  db-data:
    driver: local
